version: '3'
services:
  backend-1:
    build: ./server
    environment:
      - PORT=5050
      - SERVER="T-Rex"
    networks:
      - loadbalancing
  backend-2:
    build: ./server
    environment:
      - PORT=5050
      - SERVER="Raptor"
    networks:
      - loadbalancing
  backend-3:
    build: ./server
    environment:
      - PORT=5050
      - SERVER="Bronto"
    networks:
      - loadbalancing
  backend-4:
    build: ./server
    environment:
      - PORT=5050
      - SERVER="Stega"
    networks:
      - loadbalancing
  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - loadbalancing
    depends_on:
      - backend-1
      - backend-2
      - backend-3
      - backend-4
networks:
  loadbalancing: